### ISSUE TITLE
Operation not permitted (macOS 11.4)

### ISSUE THREAD

**Issue by Brwinded** [Moonvy/figmaEX#14]
Operation not permitted (macOS 11.4)

![photo_2021-06-24_17-40-33](https://user-images.githubusercontent.com/9316571/123282572-4f82d000-d513-11eb-88a7-73eafcd6ed9f.jpg)

How can i fix it ? (I made Terminal file access, and try with sudo )

**Comment by yArna** [comment]
you can try checking the permissions of the folder `/Applications/Figma.app`
on your Mac, open  "Applications/Figma.app" folder,   then choose File > Get Info.
![image](https://user-images.githubusercontent.com/82231420/123283529-0eec7c00-d53e-11eb-99b3-1e1b98d50bb2.png)

**Comment by Brwinded** [comment]
![photo_2021-06-24_18-41-49](https://user-images.githubusercontent.com/9316571/123292607-e2276d00-d51b-11eb-987c-942918df1918.jpg)
Read & Write

**Comment by yArna** [comment]
Have you tried executing the program by double-clicking directly in the Finder?

**Comment by Brwinded** [comment]
Sure! Unpacked the archive, opened the file from the finder. And I tried to open with sudo command from terminal

![photo_2021-06-24_19-26-27](https://user-images.githubusercontent.com/9316571/123299763-88767100-d522-11eb-892a-b74134f45428.jpg)

**Comment by yArna** [comment]
`\ 5` What does it mean?
 
![image](https://user-images.githubusercontent.com/82231420/123300696-680fdc00-d54d-11eb-9e47-28bbbb063eb3.png)

**Comment by yArna** [comment]
I'm sorry I don't know how this happened for now, but I will refactor this installer in the near future

**Comment by yArna** [comment]
We have re-released the installer, you can try it

https://github.com/Moonvy/figmaEX/releases/tag/v1.2.3
