### ISSUE TITLE
Figma Beta 101.3

### ISSUE THREAD

**Issue by Brwinded** [Moonvy/figmaEX#20]
Hi not working in the latest Figma Beta app update (101.3)
This is probably because the _codesign file is missing

**Comment by yArna** [comment]
Figma seems to have added a file integrity check
We will try the new installation mechanism

**Comment by yArna** [comment]
@Brwinded 
 The new installer should solve this problem
https://github.com/Moonvy/figmaEX/releases/tag/v1.2.6
