### ISSUE TITLE
Please remove copyrighted Figma app

### ISSUE THREAD

**Issue by poiru** [Moonvy/figmaEX#21]
Figma kindly asks you to remove https://github.com/Moonvy/figmaEX/releases/tag/v1.2.6_full

Our Figma desktop app is copyrighted and we do not allow it to be redistributed with modifications.

Please see: https://www.figma.com/copyright-and-ip-policy/

**Comment by yArna** [comment]
Yes, thanks for the information

Thanks for the information

yes, we will abide by this Policy，Remove this release

**Comment by poiru** [comment]
Thanks!
