### ISSUE TITLE
Figma doesn't open after install FigmaEX

### ISSUE THREAD

**Issue by imaniy1994** [Moonvy/figmaEX#22]
I'm after install **figmaEx** try to open **figma** but not work and doesn't show error :(

**Figma** version: v101.6
**FigmaEx** version: v1.2.5

I'm not problem a month ago and i **Love** this Plugin.

I feel after update **figma** to v101.6 this problem arose.

**Comment by sxchacha** [comment]
Because of the restrictions added to Figma Desktop App v101.6 and above Cannot be installed on Figma Desktop App v101.6 or above If you need to use it, please download the lower version of Figma Desktop App.

SEE : https://github.com/Moonvy/figmaEX/blob/master/figma-desktop-help.md
