### ISSUE TITLE
Links from menu doesn't works properly

### ISSUE THREAD

**Issue by Flashwalker** [Moonvy/figmaEX#23]
Links from popup menu doesn't works properly.  
Version: [v1.2.7](https://github.com/Moonvy/figmaEX/releases/tag/v1.2.5)  
Figma version: 99  
You just get the main menu opened.  

![4Ll7UMkhXW](https://user-images.githubusercontent.com/2188215/132508225-f78faac0-407a-4585-9b7f-d0dc34d013a9.jpg)  
![6tV5R50qCr](https://user-images.githubusercontent.com/2188215/132508259-42d7989e-0313-4a97-8ebc-e363997b4cdd.png)  

And why Figma shows v1.2.7 installed although i used v1.2.5?
![D5lzIjonsp](https://user-images.githubusercontent.com/2188215/133046055-874efa15-12fa-4ef2-9811-902ce8ca0760.png)  
How can i get v1.2.5 without autoupdates?

**Comment by yArna** [comment]
Figma's update caused its failure.
we fix it in [v1.2.8](https://github.com/Moonvy/figmaEX/releases/tag/v1.2.8)

**Comment by yArna** [comment]
see new release [v1.2.9](https://github.com/Moonvy/figmaEX/releases/tag/v1.2.9)
