### ISSUE TITLE
FigmaEX Chrome extension 汉化显示异常

### ISSUE THREAD

**Issue by guocaoyi** [Moonvy/figmaEX#38]
## FigmaEX Chrome extension 汉化显示异常

**问题描述**：误将开发模式下的 Android Compose 代码的访问符转为全角的句号（仅显示有问题，复制代码正常）
**环境**：macOS 14.2.1
**浏览器**：Chrome(version: Version 122.0.6261.94 (Official Build) (x86_64))
**复现频率**：每次
**步骤**：插件开启 > Figma file > Dev mode > click Elecment > Code (select Android Compose)

<img width="341" alt="Xnip2024-03-07_12-14-02" src="https://github.com/Moonvy/figmaEX/assets/41823509/7b742815-4dcb-4f06-83d6-d6abe95ab5fa">

希望对特定的 `<code/>` 节点不进行汉化

**Comment by yArna** [comment]
感谢反馈，在 1.4.15 版本后修复了这个问题
