### ISSUE TITLE
能否加入touch bar 的 支持

### ISSUE THREAD

**Issue by kailous** [Moonvy/figmaEX#9]
这个功能 简直是 千呼万唤使出来
但是 如果 能加入 touch bar的 支持 可以选择 显示在 touch bar 就完美了
13寸的 macbook 屏幕 空间不是很大 显示在touch bar的话 就可以节约画布空间
减少界面的 干扰 更专注的做图

**Comment by shangrenxi** [comment]
兄dei，感觉今年的mbp要砍掉touchbar了，这个功能会不会有些小众了？可能开发会觉得优先级没那么高

**Comment by yArna** [comment]
对使用 touch bar 调用插件的效率抱有怀疑态度，因为大多数时候很难记住插件在哪，经常需要移动眼睛找按钮，感觉很累。

**Comment by kailous** [comment]
我觉得挺好用的啊，我自己种BTT做了，一些个人使用非常高频的就不用在插件堆里面翻来找去了。https://www.figma.com/community/file/968010666145411757/Figma-%E8%A7%A6%E6%8E%A7%E6%A0%8F%EF%BC%88Figma-touch-bar%EF%BC%89

**Comment by kailous** [comment]
> touchbar

认为应该不会被砍掉吧，很少看到苹果
